version: "3.9"

services:
  counter-service:
    build:
      context: .
      dockerfile: DivisorCounter/Dockerfile
    depends_on:
      - cache-db
      - cache-service
    restart: on-failure
  cache-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "cache-database"
      MYSQL_USER: "div-cache"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  cache-service:
    build:
      context: .
      dockerfile: CacheService/Dockerfile
    deploy:
      replicas: 2
    depends_on:
      - cache-db
    restart: on-failure